print("<------ CS303 MACHINE LEARNING ------>")
print("<------ FINAL PROJECT ------>")
print("<------ NBA Predictor ------>")
print("<------ COLLABORATORS ------>")
print("<------ Mihika Johorey ------>")
print("<------ Pratyush Ranjan Tiwari ------>")
print("<------ Sai Vineet Reddy Thatiparthi ------>")
print("<------ End ------>")